### ISSUE TITLE
Правки ДЗ - 6

### ISSUE THREAD

**Issue by Dexter19** [olhovoiivan/IvanOlhovoi#2]
Пункт 4 -- Встановіть першому елементу li помаранчевий колір(це не обов'язково але можна написати простіше)
У вас стилі виглядають так:
body > ul:nth-child(3){
        li:first-child{
        color:orange;
        }
    }
Можна простіше так:
li:first-child {
   color: orange;
}
і в наступних пунтах теж.
-----------------------

**Comment by olhovoiivan** [comment]
Спробував - переробити, дякую
