### ISSUE TITLE
Правки/Рекомендації до ДЗ 11

### ISSUE THREAD

**Issue by Dexter19** [olhovoiivan/IvanOlhovoi#3]
Створіть сітку з 3-х колонок.
Налаштуйте grid-властивості так, щоб header займав 3 колонки, main - 2 колонки, footer - 3 колонки.
 Як альтернатива ще можна записати так:
.grid-container {
    display: grid;
    grid-gap: 20px;
}

.grid-container {
    grid-template-columns: repeat(3, 1fr);
}

.header {
    grid-column: span 3;
}

.main {
    grid-column: span 2;
}

.footer {
    grid-column: span 3;
}
---------------------------

**Comment by olhovoiivan** [comment]
Дякую, виправлю
